export const COMMON_RADICALS = [
  { char: '一', pinyin: 'yī', meaning: 'Bộ Nhất (Số 1)' },
  { char: '丨', pinyin: 'gǔn', meaning: 'Bộ Cổn (Nét sổ)' },
  { char: '丶', pinyin: 'zhǔ', meaning: 'Bộ Chủ (Điểm, chấm)' },
  { char: '丿', pinyin: 'piě', meaning: 'Bộ Phiệt (Nét phẩy)' },
  { char: '乙', pinyin: 'yǐ', meaning: 'Bộ Ất (Vị trí thứ 2)' },
  { char: '亅', pinyin: 'jué', meaning: 'Bộ Quyết (Nét móc)' },
  { char: '二', pinyin: 'èr', meaning: 'Bộ Nhị (Số 2)' },
  { char: '亠', pinyin: 'tóu', meaning: 'Bộ Đầu (Dấu chấm trên đầu)' },
  { char: '人', pinyin: 'rén', meaning: 'Bộ Nhân (Người)' },
  { char: '儿', pinyin: 'ér', meaning: 'Bộ Nhi (Trẻ con)' },
  { char: '入', pinyin: 'rù', meaning: 'Bộ Nhập (Vào)' },
  { char: '八', pinyin: 'bā', meaning: 'Bộ Bát (Số 8)' },
  { char: '冂', pinyin: 'jiǒng', meaning: 'Bộ Quynh (Vùng biên giới)' },
  { char: '冖', pinyin: 'mì', meaning: 'Bộ Mịch (Trùm khăn lên)' },
  { char: '冫', pinyin: 'bīng', meaning: 'Bộ Băng (Nước đá)' },
  { char: '几', pinyin: 'jī', meaning: 'Bộ Kỷ (Ghế dựa)' },
  { char: '凵', pinyin: 'kǎn', meaning: 'Bộ Khảm (Há miệng)' },
  { char: '刀', pinyin: 'dāo', meaning: 'Bộ Đao (Con dao)' },
  { char: '力', pinyin: 'lì', meaning: 'Bộ Lực (Sức mạnh)' },
  { char: '勹', pinyin: 'bāo', meaning: 'Bộ Bao (Bao bọc)' },
  { char: '匕', pinyin: 'bǐ', meaning: 'Bộ Chủy (Cái thìa)' },
  { char: '匚', pinyin: 'fāng', meaning: 'Bộ Phương (Tủ đựng)' },
  { char: '十', pinyin: 'shí', meaning: 'Bộ Thập (Số 10)' },
  { char: '卜', pinyin: 'bǔ', meaning: 'Bộ Bốc (Xem bói)' },
  { char: '卩', pinyin: 'jié', meaning: 'Bộ Tiết (Đốt tre)' },
  { char: '厂', pinyin: 'hǎn', meaning: 'Bộ Hán (Sườn núi)' },
  { char: '厶', pinyin: 'sī', meaning: 'Bộ Tư (Riêng tư)' },
  { char: '又', pinyin: 'yòu', meaning: 'Bộ Hựu (Lại nữa, bàn tay)' },
  { char: '口', pinyin: 'kǒu', meaning: 'Bộ Khẩu (Cái miệng)' },
  { char: '囗', pinyin: 'wéi', meaning: 'Bộ Vi (Vây quanh)' },
  { char: '土', pinyin: 'tǔ', meaning: 'Bộ Thổ (Đất)' },
  { char: '士', pinyin: 'shì', meaning: 'Bộ Sĩ (Kẻ sĩ)' },
  { char: '夂', pinyin: 'zhǐ', meaning: 'Bộ Truy (Đi chậm)' },
  { char: '夕', pinyin: 'xī', meaning: 'Bộ Tịch (Đêm tối)' },
  { char: '大', pinyin: 'dà', meaning: 'Bộ Đại (Lớn)' },
  { char: '女', pinyin: 'nǚ', meaning: 'Bộ Nữ (Phụ nữ)' },
  { char: '子', pinyin: 'zǐ', meaning: 'Bộ Tử (Con cái)' },
  { char: '宀', pinyin: 'mián', meaning: 'Bộ Miên (Mái nhà)' },
  { char: '寸', pinyin: 'cùn', meaning: 'Bộ Thốn (Tấc Anh, đơn vị đo)' },
  { char: '小', pinyin: 'xiǎo', meaning: 'Bộ Tiểu (Nhỏ)' },
  { char: '尸', pinyin: 'shī', meaning: 'Bộ Thi (Xác chết)' },
  { char: '山', pinyin: 'shān', meaning: 'Bộ Sơn (Núi)' },
  { char: '工', pinyin: 'gōng', meaning: 'Bộ Công (Công việc)' },
  { char: '己', pinyin: 'jǐ', meaning: 'Bộ Kỷ (Bản thân)' },
  { char: '巾', pinyin: 'jīn', meaning: 'Bộ Cân (Cái khăn)' },
  { char: '干', pinyin: 'gān', meaning: 'Bộ Can (Thiên can, khô)' },
  { char: '广', pinyin: 'guǎng', meaning: 'Bộ Nghiễm (Mái nhà bên sườn núi)' },
  { char: '彐', pinyin: 'jì', meaning: 'Bộ Ký (Đầu con nhím)' },
  { char: '弓', pinyin: 'gōng', meaning: 'Bộ Cung (Cái cung)' },
  { char: '彳', pinyin: 'chì', meaning: 'Bộ Xích (Bước chân trái)' },
];
